theme: jekyll-theme-minimal

title: Sophie Shaw
description: Bioinformatician 

avatar: https://github.com/SophieS9/sophies9.github.io/Sophie_Shaw_Photo.jpg

footer-links:
  email: s.shaw@abdn.ac.uk
  github: SophieS9
  twitter: Sophie_S9 
