theme: jekyll-theme-minimal

title: Sophie Shaw
description: Bioinformatician 

avatar: https://github.com/SophieS9/sophies9.github.io/Sophie_Shaw_Photo.jpg

email: s.shaw@abdn.ac.
github: SophieS9
twitter: Sophie_S9 
